apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings
spec:
  selector:
    matchLabels:
      my-label: label
  template:
    metadata:
      labels:
        my-label: label
    spec:
      containers:
      - name: settings
        image: dfedde/my-app
        env:
        - name: REDIS_HOST
          value: redis-service.default.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 4567
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: blueis # has to match .spec.template.metadata.labels
  serviceName: "redis-service"
  template:
    metadata:
      labels:
        app: blueis # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: redis
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
  selector:
    app: blueis
